<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "comsolit_suggest"
 *
 * Auto generated by Extension Builder 2015-06-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'comsolit Suggest',
	'description' => 'This Plugin extends the searchform with an suggest/autocomplete feature of words indexed from Ext:indexed_search based on a ajax request and typeahead lib',
	'category' => 'plugin',
	'author' => 'Andres Lobacovs, comsolit AG',
	'author_email' => 'info@comsolit.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.3.99',
			'indexed_search' => '6.2.0-7.3.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
